services:
  app:
    networks:
      - webserver_proxynet
    image: ghcr.io/wafflethief123/publictransit-systems:main
    container_name: publictransit-app
    environment:
      - INCIDENTS_WORKER_URL=https://wmata-incidents.capitolhostingsolutions.workers.dev
    restart: unless-stopped

networks:
  webserver_proxynet:
    external: true
