name = "transit-incidents"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "980848d7b4694e0fa4034bc45954e11a"

# Cron trigger - runs every hour
[triggers]
crons = ["0 * * * *"]

# KV namespace for storing incident data
[[kv_namespaces]]
binding = "INCIDENTS_KV"
id = "59f9eb02730d43528e63fb15ca2e151c"

[vars]
CORS_ORIGIN = "*"
